window.Gameplot=class Gameplot{
 constructor({games,onSelect}){this.games=games;this.onSelect=onSelect;this.now=new Date();this.view={target:[0,50,0],zoom:3.05};this.teamFilter=new Set;this.width=innerWidth;this.height=innerHeight;const el=document.getElementById('deck-container');this.deck=new deck.Deck({parent:el,views:new deck.OrthographicView({id:'plot'}),viewState:this.view,controller:{dragPan:true,dragRotate:false,scrollZoom:true,touchZoom:true,inertia:400},onViewStateChange:e=>{this.view=e.viewState;this.render()},onHover:i=>this.hover(i)});el.addEventListener('pointerdown',e=>{this.pointerStart=[e.clientX,e.clientY]},true);el.addEventListener('pointerup',e=>{const p=this.pointerStart;this.pointerStart=null;if(p&&Math.hypot(e.clientX-p[0],e.clientY-p[1])<7)this.hit(e)},true);el.addEventListener('pointerleave',()=>this.hideTooltip(),true);this.render()}
 x(g){return this.focusTime((g.time-this.now)/864e5)} focusTime(days){const sign=Math.sign(days),abs=Math.abs(days);return abs<=1?days*70:sign*(70+(abs-1)*.55)} unfocusTime(x){const sign=Math.sign(x),abs=Math.abs(x);return sign*(abs<=70?abs/70:1+(abs-70)/.55)} score(g){return g.completed?(g.__mwRevealed?g.displayScore:50):g.anticipation} y(s){return 50-(s-50)*.52} setTeamFilter(t){this.teamFilter=new Set(t);this.render()}
 compact(){const scale=2**this.view.zoom,gap=27/scale,items=this.games.map((g,i)=>({source:g,x:this.x(g),y:this.y(this.score(g)),i})).sort((a,b)=>String(a.source.id).localeCompare(String(b.source.id))),placed=[];const offsets=[[0,0]];for(let ring=1;ring<=6;ring++)for(let step=0;step<ring*6;step++){const angle=step/(ring*6)*Math.PI*2+ring*.37;offsets.push([Math.cos(angle)*gap*ring,Math.sin(angle)*gap*ring])}items.forEach(item=>{let point;for(const [dx,dy] of offsets){const candidate={vx:item.x+dx,vy:item.y+dy};if(placed.every(other=>Math.hypot(candidate.vx-other.vx,candidate.vy-other.vy)>=gap*.74)){point=candidate;break}}placed.push({...item,...(point||{vx:item.x,vy:item.y}),members:[item.source],anchor:[item.x,item.y]})});return placed}
 visible(d){return!this.teamFilter.size||d.members.some(g=>this.teamFilter.has(g.home)||this.teamFilter.has(g.away))}
 pod(d){const g=d.members[0];return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="150" height="72"><clipPath id="c"><circle cx="75" cy="36" r="30"/></clipPath><g clip-path="url(#c)"><rect x="45" y="6" width="30" height="60" fill="${g.homeColor}"/><rect x="75" y="6" width="30" height="60" fill="${g.awayColor}"/></g><circle cx="75" cy="36" r="30" fill="none" stroke="#f3efe5" stroke-width="2"/></svg>`)}`}
 countdown(g){const m=Math.round((g.time-this.now)/60000),a=Math.abs(m),prefix=m<0?'AGO ':'';const value=a<60?`${Math.max(1,a)}M`:a<1440?`${Math.ceil(a/60)}H`:a<10080?`${Math.ceil(a/1440)}D`:g.time.toLocaleDateString(undefined,{month:'short',day:'numeric'});return m<0?`${value} AGO`:`IN ${value}`}
 render(){const data=this.compact(),z=this.view.zoom,size=Math.max(30,Math.min(58,34+(z-3)*12)),scale=2**z,left=this.view.target[0]-this.width/(2*scale)+2,alpha=d=>this.visible(d)?255:25;const layers=[new deck.LineLayer({id:'guides',data:[25,50,75],getSourcePosition:s=>[-300,this.y(s)],getTargetPosition:s=>[300,this.y(s)],getColor:s=>[243,239,229,s===50?20:9],getWidth:1}),new deck.TextLayer({id:'axis',data:[{s:75,t:'75  STRONG'},{s:50,t:'50  NEUTRAL'},{s:25,t:'25  LOW'}],getPosition:d=>[left,this.y(d.s)],getText:d=>d.t,getSize:9,getColor:[243,239,229,90],fontFamily:'DM Mono'}),new deck.IconLayer({id:'pods',data,pickable:true,getIcon:d=>({url:this.pod(d),width:150,height:72,anchorX:75,anchorY:36}),getPosition:d=>[d.vx,d.vy],getSize:size,sizeUnits:'pixels',getColor:d=>[255,255,255,alpha(d)]})];const badges=data.flatMap(d=>{const g=d.members[0];return[{...d,logo:g.homeMapLogo||g.homeLogo,dx:-11},{...d,logo:g.awayMapLogo||g.awayLogo,dx:11}]}).filter(d=>d.logo&&!/\.svg(?:$|\?)/i.test(d.logo));layers.push(new deck.IconLayer({id:'badges',data:badges,getIcon:d=>({url:d.logo,width:64,height:64,anchorX:32,anchorY:32}),getPosition:d=>[d.vx,d.vy],getSize:18,sizeUnits:'pixels',getPixelOffset:d=>[d.dx,0],getColor:d=>[255,255,255,alpha(d)]}));const upcoming=data.filter(d=>!d.members[0].completed&&this.x(d.members[0])<10).sort((a,b)=>a.x-b.x).slice(0,8);layers.push(new deck.LineLayer({id:'imminent-connectors',data:upcoming,getSourcePosition:d=>[d.vx,50],getTargetPosition:d=>[d.vx,d.vy],getColor:[243,239,229,38],getWidth:1}),new deck.TextLayer({id:'countdowns',data:upcoming,getPosition:d=>[d.vx,d.vy],getText:d=>this.countdown(d.members[0]),getSize:9,getColor:[243,239,229,210],fontFamily:'DM Mono',pixelOffset:[0,-size/2-10],getTextAnchor:'middle'}));this.deck.setProps({viewState:this.view,layers});this.chrome()}
 hit(e){const r=e.currentTarget.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top,s=2**this.view.zoom;let best=48,hit;this.compact().forEach(d=>{const dist=Math.hypot((d.vx-this.view.target[0])*s+this.width/2-px,(d.vy-this.view.target[1])*s+this.height/2-py);if(dist<best){best=dist;hit=d}});if(hit)this.click(hit)}
 click(d){const g=d.members[0];if(g.completed&&!g.__mwRevealed)this.activate(g);else if(g.completed)this.onSelect(g,g.scoreResult,true)}
 activate(g){
   // A completed fixture needs its provider detail before a Spoil Meter value
   // is shown. Do not reveal a fixture-only fallback first: it can be a stale
   // zero while the events and scorecard are still arriving.
   if(g.__watchCalculating||g._watchLoading)return;
   g._watchLoading=true;
   g.__watchCalculating=true;
   this.onSelect(g,null,false)
 }
 reveal(g,s){const score=Math.round(Number(s?.watchScore));if(!Number.isFinite(score))return;g.scoreResult={...s,watchScore:score};g.displayScore=score;g.__mwRevealed=true;this.render()}
 hideTooltip(){this.deck.setProps({getTooltip:()=>null});const tip=document.querySelector('.deck-tooltip');if(tip)tip.style.display='none'}
 hover(i){if(!i.object){this.hideTooltip();return}const tip=document.querySelector('.deck-tooltip');if(tip)tip.style.display='';const d=i.object;if(d.cluster){const rows=d.members.map(g=>{const hidden=g.completed&&!g.__mwRevealed,score=hidden?'?':g.completed?(g.scoreResult?.watchScore??'—'):g.anticipation;return{g,score,order:hidden?-1:Number(score)||0}}).sort((a,b)=>b.order-a.order).map(({g,score})=>{const date=g.time.toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});return `<div class="cluster-row"><b class="cluster-score">${score}</b><span class="cluster-fixture"><span class="cluster-badges"><img src="${g.homeLogo||''}"><img src="${g.awayLogo||''}"></span><span>${g.homeAbbr||g.home} v ${g.awayAbbr||g.away}</span></span><em><strong>${this.countdown(g)}</strong><small>${date}</small></em></div>`}).join('');this.deck.setProps({getTooltip:()=>({html:`<div class="hover-card cluster-card"><span class="hover-kicker">${d.members.length} MATCHES AT THIS MOMENT</span><div class="cluster-rows">${rows}</div><span>Click to open this pocket of time.</span></div>`})});return}const g=d.members[0],hidden=g.completed&&!g.__mwRevealed,score=hidden?'?':g.completed?(g.scoreResult?.watchScore??'—'):g.anticipation,date=g.time.toLocaleString(undefined,{weekday:'short',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}),b=g.anticipationBreakdown||{},meter=(label,value)=>`<label><span>${label}</span><b><i style="width:${value||0}%"></i></b><em>${value||'—'}</em></label>`,bars=!g.completed?`<div class="preview-bars">${meter('COMPETITIVENESS',b.competitiveness)}${meter('TABLE CONTEXT',b.tableContext)}${meter('SEASON TIMING',b.seasonTiming)}</div>`:'',notes=!g.completed?[g.league&&g.venue?`${g.league} · ${g.venue}`:g.league,g.injuries?.length?`INJURY REPORT · ${g.injuries.length} UPDATE${g.injuries.length===1?'':'S'}`:null,g.rosters?.length?'SQUAD INFORMATION AVAILABLE':null].filter(Boolean):[];this.deck.setProps({getTooltip:()=>({html:`<div class="hover-card"><span class="hover-kicker">${this.countdown(g)}</span><strong class="hover-score">${score}</strong><b class="hover-match"><img src="${g.homeLogo}">${g.homeAbbr||g.home}<br><img src="${g.awayLogo}">${g.awayAbbr||g.away}</b><span>${date}</span>${!g.completed?`${notes.map(note=>`<span>${note}</span>`).join('')}${bars}`:hidden?'Click to reveal':'Click for match notes'}</div>`})})}
 chrome(){const s=2**this.view.zoom,nx=(0-this.view.target[0])*s+this.width/2;document.getElementById('now-line').style.left=`${nx}px`;const focus=document.getElementById('focus-window'),start=(this.focusTime(-1)-this.view.target[0])*s+this.width/2,end=(this.focusTime(1)-this.view.target[0])*s+this.width/2;focus.style.left=`${start}px`;focus.style.width=`${end-start}px`;const live=this.games.filter(game=>game.live&&!game.completed),zone=document.getElementById('live-zone');if(live.length){const positions=live.map(game=>(this.x(game)-this.view.target[0])*s+this.width/2),left=Math.max(0,Math.min(...positions)-44),right=Math.min(this.width,Math.max(...positions)+44);zone.hidden=false;zone.style.left=`${left}px`;zone.style.width=`${Math.max(88,right-left)}px`}else zone.hidden=true;const ticks=document.getElementById('focus-ticks'),mid=this.height/2+(this.y(50)-this.view.target[1])*s;ticks.innerHTML='';let lastTime=-Infinity;for(let hour=-24;hour<=24;hour+=3){const x=(this.focusTime(hour/24)-this.view.target[0])*s+this.width/2;if(x<0||x>this.width||x-lastTime<68)continue;const time=new Date(+this.now+hour*36e5).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'}),e=document.createElement('span');e.className='focus-tick';e.style.left=`${x}px`;e.style.top=`${mid}px`;e.textContent=hour===0?`NOW · ${time}`:time;ticks.append(e);lastTime=x}const a=document.getElementById('time-axis');a.innerHTML='';const focusDate=document.createElement('span');focusDate.className='date-tick focus-date';focusDate.style.left=`${nx}px`;focusDate.innerHTML=`<label>${this.now.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})} · 48H FOCUS</label>`;a.append(focusDate);const seen=new Set;let lastDate=-Infinity;for(let x=Math.floor((this.view.target[0]-this.width/s/2)/4)*4;x<this.view.target[0]+this.width/s/2;x+=4){const l=(x-this.view.target[0])*s+this.width/2,raw=this.unfocusTime(x),day=new Date(+this.now+raw*864e5),label=day.toLocaleDateString(undefined,{month:'short',day:'numeric'});if(l<0||l>this.width||Math.abs(raw)<=1||seen.has(label)||l-lastDate<84)continue;seen.add(label);lastDate=l;const e=document.createElement('span');e.className='date-tick';e.style.left=`${l}px`;e.innerHTML=`<label>${label}</label>`;a.append(e)}}
 recenter(){this.view={...this.view,target:[0,50,0],transitionDuration:700,transitionInterpolator:new deck.LinearInterpolator(['target','zoom'])};this.render()}
};
